//#define WALL_PLANE -21
//#define FLOOR_PLANE -20
#define FLOOR_PLANE_RENDER_TARGET "FLOOR_PLANE"
#define FLOOR_PLANE_FOV_HIDDEN -19
//#define GAME_PLANE -18
#define GAME_PLANE_BLOOM -17
#define GAME_PLANE_WINDOW -16
#define GAME_PLANE_ABOVE_WINDOW -15 //this hurts me profoundly, but it's necessary
#define GAME_PLANE_FOV_HIDDEN -14
#define GAME_PLANE_UPPER -13
#define GAME_PLANE_UPPER_BLOOM -12
#define GAME_PLANE_UPPER_FOV_HIDDEN -11
#define GAME_PLANE_OBJECT_PERMANENCE -10
//#define ABOVE_GAME_PLANE -9
#define POLLUTION_PLANE -8
#define RIPPLE_PLANE -7
#define FRILL_PLANE_WINDOW -6
#define FRILL_PLANE_LOW -5
#define FRILL_PLANE -4
#define FRILL_RENDER_TARGET "FRILL_PLANE"
#define ABOVE_FRILL_PLANE -3
#define ABOVE_FRILL_PLANE_BLOOM -2

#define ATOMS_FOV_SHADOWS_PLANE 330
#define WALLS_FOV_PLANE_0 331
#define WALLS_FOV_PLANE_1 332
#define WALLS_FOV_PLANE_2 333
#define WALLS_FOV_PLANE_3 334
#define WALLS_FOV_PLANE_4 335
#define WALLS_FOV_PLANE_5 336
#define WALLS_FOV_PLANE_6 337
#define WALLS_FOV_PLANE_7 338
#define WALLS_FOV_PLANE_8 339
#define WALLS_FOV_PLANE_9 340

//I stole this from Kapu of Daedalus. I don't know where he got it from though.
#define ATOMS_FOV_SHADOWS_RENDER_TARGET "*ATOMS_FOV_SHADOWS_PLANE"
#define WALLS_FOV_PLANE_0_RENDER_TARGET "*WALLS_FOV_PLANE_0"
#define WALLS_FOV_PLANE_1_RENDER_TARGET "*WALLS_FOV_PLANE_1"
#define WALLS_FOV_PLANE_2_RENDER_TARGET "*WALLS_FOV_PLANE_2"
#define WALLS_FOV_PLANE_3_RENDER_TARGET "*WALLS_FOV_PLANE_3"
#define WALLS_FOV_PLANE_4_RENDER_TARGET "*WALLS_FOV_PLANE_4"
#define WALLS_FOV_PLANE_5_RENDER_TARGET "*WALLS_FOV_PLANE_5"
#define WALLS_FOV_PLANE_6_RENDER_TARGET "*WALLS_FOV_PLANE_6"
#define WALLS_FOV_PLANE_7_RENDER_TARGET "*WALLS_FOV_PLANE_7"
#define WALLS_FOV_PLANE_8_RENDER_TARGET "*WALLS_FOV_PLANE_8"
#define WALLS_FOV_PLANE_9_RENDER_TARGET "*WALLS_FOV_PLANE_9"
#define FOV_WALL_ICON '_horizon/walls_fov3.dmi'
